import numpy as np 
arr=np.arange(1,10)
print("array: ", arr)
print("shape: ", arr.shape)
print("size: ", arr.size)
print("datatype: ", arr.dtype)
print("first element: ", arr[0])
print("last element: ", arr[-1])
print("fist 5 element: ", arr[0:6])
print("last 3 element: ", arr[-3:])
arr1=np.zeros(5)
print("5 zeros: ", arr1)
arr2=np.ones(6)
print("6 ones :", arr2)